openapi: 3.0.3
info:
  title: Red Flag Radar API - List Flags
  version: 1.0.0
  description: Retrieve red flags with filtering, sorting, and pagination

paths:
  /api/{entityType}/{id}/red-flags:
    get:
      summary: List red flags for an entity
      operationId: listRedFlags
      parameters:
        - name: entityType
          in: path
          required: true
          schema:
            type: string
            enum: [companies, data-rooms]
          description: Type of entity (companies or data-rooms)

        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Entity ID (company_id or data_room_id)

        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [open, reviewing, mitigating, resolved, false_positive]
          description: Filter by flag status (comma-separated for multiple)

        - name: category
          in: query
          required: false
          schema:
            type: string
            enum: [financial, legal, operational, cyber, esg]
          description: Filter by flag category (comma-separated for multiple)

        - name: severity
          in: query
          required: false
          schema:
            type: string
            enum: [critical, high, medium, low]
          description: Filter by severity (comma-separated for multiple)

        - name: search
          in: query
          required: false
          schema:
            type: string
          description: Search in title and description (case-insensitive)

        - name: sort
          in: query
          required: false
          schema:
            type: string
            enum: [severity, confidence, updated, detected]
            default: severity
          description: Sort field

        - name: order
          in: query
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          description: Sort order

        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number (1-indexed)

        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Items per page

      responses:
        '200':
          description: List of red flags
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - pagination
                  - summary
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/RedFlagListItem'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
                  summary:
                    $ref: '#/components/schemas/FlagSummary'

        '401':
          description: Unauthorized - authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden - user lacks access to entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '404':
          description: Entity not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    RedFlagListItem:
      type: object
      required:
        - id
        - category
        - title
        - severity
        - status
        - first_detected_at
        - last_updated_at
      properties:
        id:
          type: string
          format: uuid
        category:
          type: string
          enum: [financial, legal, operational, cyber, esg]
        title:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        severity:
          type: string
          enum: [critical, high, medium, low]
        confidence:
          type: number
          minimum: 0
          maximum: 1
          nullable: true
        status:
          type: string
          enum: [open, reviewing, mitigating, resolved, false_positive]
        first_detected_at:
          type: string
          format: date-time
        last_updated_at:
          type: string
          format: date-time
        owner:
          type: object
          nullable: true
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
            email:
              type: string
              format: email
        evidence_preview:
          type: array
          maxItems: 3
          items:
            type: object
            properties:
              type:
                type: string
                enum: [document, alert, signal, kpi, news]
              title:
                type: string
              preview:
                type: string
                maxLength: 200
        is_snoozed:
          type: boolean

    Pagination:
      type: object
      required:
        - page
        - limit
        - total
        - total_pages
      properties:
        page:
          type: integer
          minimum: 1
        limit:
          type: integer
          minimum: 1
          maximum: 100
        total:
          type: integer
          minimum: 0
        total_pages:
          type: integer
          minimum: 0

    FlagSummary:
      type: object
      required:
        - total
        - by_category
        - by_severity
        - by_status
      properties:
        total:
          type: integer
          minimum: 0
        by_category:
          type: object
          properties:
            financial:
              type: integer
            legal:
              type: integer
            operational:
              type: integer
            cyber:
              type: integer
            esg:
              type: integer
        by_severity:
          type: object
          properties:
            critical:
              type: integer
            high:
              type: integer
            medium:
              type: integer
            low:
              type: integer
        by_status:
          type: object
          properties:
            open:
              type: integer
            reviewing:
              type: integer
            mitigating:
              type: integer
            resolved:
              type: integer
            false_positive:
              type: integer

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true
