import React from 'react'
import { View, Text } from '@react-pdf/renderer'
import { pdfStyles } from '../styles/pdf-styles'

interface FooterProps {
  generatedBy: string
  generatedAt: string
  searchParameters?: {
    regions?: string[]
    industries?: string[]
    weights?: Record<string, number>
  }
  pageNumber: number
  totalPages: number
}

export const Footer: React.FC<FooterProps> = ({
  generatedBy,
  generatedAt,
  searchParameters,
  pageNumber,
  totalPages
}) => {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long', 
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  return (
    <View style={pdfStyles.footer} fixed>
      <View style={{ flex: 1 }}>
        <Text style={pdfStyles.footerText}>
          Generated by: {generatedBy}
        </Text>
        <Text style={pdfStyles.footerText}>
          Date: {formatDate(generatedAt)}
        </Text>
        {searchParameters && (
          <Text style={pdfStyles.footerText}>
            Parameters: {searchParameters.regions?.join(', ') || 'All regions'} | {' '}
            {searchParameters.industries?.join(', ') || 'All industries'}
          </Text>
        )}
      </View>
      
      <View style={{ alignItems: 'center' }}>
        <Text style={[pdfStyles.footerText, { fontSize: 9, color: '#3B82F6' }]}>
          oppSpot Similarity Analysis Report
        </Text>
        <Text style={pdfStyles.footerText}>
          Page {pageNumber} of {totalPages}
        </Text>
      </View>
      
      <View style={{ flex: 1, alignItems: 'flex-end' }}>
        <Text style={[pdfStyles.footerText, { color: '#3B82F6' }]}>
          oppspot.com
        </Text>
        <Text style={pdfStyles.footerText}>
          AI-Powered Business Intelligence
        </Text>
      </View>
    </View>
  )
}